language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

env:
  - SYMFONY_VERSION=2.6.*

before_script:
    - composer self-update || true
    - composer install --dev --prefer-source

script:
  - bin/atoum

notifications:
  email:
    - thomas@scullwm.com